### ISSUE TITLE
Attemp to compare nil value

### ISSUE THREAD

**Issue by Dokman** [ESX-Org/esx_property#105]
Hi guys i am having this error with latest es_extended
![image](https://user-images.githubusercontent.com/2290904/82214272-d9766780-9915-11ea-94a4-d381707d9de6.png)

How i can fix it?

the code is this

![image](https://user-images.githubusercontent.com/2290904/82214328-f317af00-9915-11ea-9657-6303f9f18a3c.png)

Code:

```
RegisterServerEvent('esx_property:buyProperty')
AddEventHandler('esx_property:buyProperty', function(propertyName)

  local xPlayer  = ESX.GetPlayerFromId(source)
  local property = GetProperty(propertyName)

  if property.price <= xPlayer.get('money') then

    xPlayer.removeMoney(property.price)
    SetPropertyOwned(propertyName, property.price, false, xPlayer.identifier)

  else
    TriggerClientEvent('esx:showNotification', source, _U('not_enough'))
  end

end)
```

**Comment by sergio-atilano** [comment]
@Dokman change

`if property.price <= xPlayer.get('money') then`

to 

`if property.price <= xPlayer.getMoney() then`

and it will be fixed

**Comment by Dokman** [comment]
any recomended IDE to watch and fix errors?
