### ISSUE TITLE
you did not pay a security deposit

### ISSUE THREAD

**Issue by jcollins012** [ESX-Org/esx_property#14]
after time i sign into the game it comes up with a prompt saying i didnt pay a security deposit.. im not sure what i can do to fix this, do you have any suggestions.. thanks in advance

**Comment by ElPumpo** [comment]
Also getting this...

**Comment by bendenny** [comment]
Also getting this

**Comment by dracuslayer** [comment]
getting this as well

**Comment by ElPumpo** [comment]
This is from esx_jobs which has been fixed already.
