### ISSUE TITLE
Issue adding property to the database

### ISSUE THREAD

**Issue by eagledude4** [ESX-Org/esx_property#16]
SQL Entry: 
`'43', 'Clubhouse2', 'Club House 2', '{\"x\":-1447.06,\"y\":-538.28,\"z\":33.74}', '{\"x\":997.699,\"y\":-3158.15,\"z\":-39.857}', '{\"x\":997.699,\"y\":-3158.15,\"z\":-39.857}', '{\"x\":-1447.06,\"y\":-538.28,\"z\":33.74}', '[\"bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo\"]', NULL, '1', '1', '0', '{\"x\":-1457.026,\"y\":-530.219,\"z\":55.937}', '1700000'
`
The map and world markers appear, but when i enter the marker, I don't get an option to use the teleport

**Comment by dracuslayer** [comment]
I get the same thing unable to add properties.
