### ISSUE TITLE
Office's marker's Glitch 

### ISSUE THREAD

**Issue by HeQu11** [ESX-Org/esx_property#18]
hello I found or only I have a bug with offices how to buy an office and I will come to him then two markers overlap and it is impossible to leave if someone has a working sql and sends it to me I will be very grateful

![zrzut ekranu 618](https://user-images.githubusercontent.com/32333860/36994104-583459e6-20b0-11e8-8f48-925dff929f81.png)

**Comment by ElPumpo** [comment]
I'm certian it was fixed in #17, closing
