### ISSUE TITLE
Player spawn inside apartment, some bugs.

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_property#25]
1. When someone join on the server and is in the apartment he can not get out of it.
2. Sometimes when someone enters the apartment he is moved to the last position in which he was dead. (But he is invisible then).

**Comment by TemptressTeelia** [comment]
Hello, 
So what has happened is that there are no coordinates for the exit of the instance. 
You need to go to the database and input the coordinates of the exit. 
This happened to my character when testing and I was stuck in one of the offices. 
So you might have to check the offices as well. Make sure every property has a exit coordinate in the database. 

Hope that helps.

**Comment by JaroSound** [comment]
My exit coordinates are fine for all properties so it cannot be the problem.

**Comment by JiminyKroket** [comment]
The issue is that the character spawns into the server itself not the 'instance' of the property. You could store them in a DB when they enter and leave properties and call to it on playerLoaded event. If they are in property then make the instance.
