### ISSUE TITLE
Only acquired properties menu ?

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_property#34]
When i want to visit a property witch more than 1 room i have only acquired properties menu.
I cant visit why? Its bugged after update?

**Comment by ElPumpo** [comment]
Please try downgrading and report back

**Comment by MrPoolz** [comment]
You guys have any updates on this matter cause i'm still having this problem...

**Comment by zelizz** [comment]
a year later and still the same problem LOL
