### ISSUE TITLE
Cannot enter the properties

### ISSUE THREAD

**Issue by daanvanderuit** [ESX-Org/esx_property#36]
Dear developer,

I've installed ESX_Property and all the required scripts. I've made sure to load all the required scripts before loading esx_property. I can see all apartments and rent / buy them without a problem. The only thing is that I can neither enter nor visit the apartments. 

What am I doing wrong? Thanks in advance.

**Comment by ElPumpo** [comment]
Start instance after this resource

**Comment by DirtyGaming** [comment]
I have the same problem

> Start instance after this resource

I'm having the same problem - I tried starting instance after this resource but the problem persists
