### ISSUE TITLE
[Player Inside] [Issue]

### ISSUE THREAD

**Issue by djowdobom** [ESX-Org/esx_property#41]
When i got inside of some **offices**, i cant move inside some, no errors appears in console, i'm using all files from esx-org and also:

**instance
cron
esx_addonaccount
esx_addoninventory
esx_datastore**

Thank you for attention.

**Comment by HumanTree92** [comment]
Its b/c your using an IPL or a Map Loader that is loading the Office Stuff. If you are using this https://forum.fivem.net/t/release-fivem-ipl/115816 or a different one. For instance in the FiveM IPL in client.lua & iplList.lua you need to comment out anything that has to do with CEO Offices. B/c with this its simply loading all the garages & offices so when you try to walk around you can move or glitching through the floor.

**Comment by djowdobom** [comment]
Thank you very much Sir, saved me a lot of trouble!
