### ISSUE TITLE
Disappearing items from property

### ISSUE THREAD

**Issue by macius2003** [ESX-Org/esx_property#53]
Items are not saving in deposit of real estate any fixes?

**Comment by HALALsnackbar** [comment]
So we are experiencing this issue as well but one thing I will mention is we use KASHacters and the people who report missing items usually have to jump through a few hoops to get them back. 

1. Restart esx_addoninventory. If that doesn't work...
2. Try switching your characters if you have more than one. If that doesn't work...
3. Ask the player to rent another apartment and check the inventory.

**Comment by BryBTG** [comment]
Does someone fix this issue?

**Comment by Ex0r** [comment]
Have you added the datastore_data table to the server.lua of KASHACTERS? It ensure that the correct character identifier is mapped to the correct property on character switch.
