### ISSUE TITLE
Possibly an addition of price tags

### ISSUE THREAD

**Issue by cxbalt** [ESX-Org/esx_property#54]
Price tags for purchasable properties, we can view rent prices but not purchase prices

**Comment by SliderKP** [comment]
That would be great

**Comment by JiminyKroket** [comment]
Its way better for the dev if you have a fix for it to post for them...

**Comment by JiminyKroket** [comment]
https://github.com/ESX-Org/esx_property/pull/64 heres the PR you can get for yourself until/if Pumpo pulls the PR

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_property/commit/96c1ab491f924fc7e454f26eeeb45d07e475ded1
