### ISSUE TITLE
F8 Error 

### ISSUE THREAD

**Issue by MackOG** [ESX-Org/esx_property#60]
![20190602144336_1](https://user-images.githubusercontent.com/50641021/58765864-5530a600-8545-11e9-9dd7-035a86f47ff5.jpg)
![20190602144345_1](https://user-images.githubusercontent.com/50641021/58765866-595cc380-8545-11e9-891f-2b87a0d74274.jpg)

Any help would be great.

**Comment by Hamza8700** [comment]
I get the same error
