### ISSUE TITLE
bug ammo duplicating

### ISSUE THREAD

**Issue by tonibanks** [ESX-Org/esx_property#78]
I am having duplicating ammo… When i stored same categories weapon example pistol with 100 bullet and heavy pistol, when i deposit the weapons yes its good ammo and gun will disappear on my inventory but when i withdraw the weapons instead 100 bullet it will become 200.

**Comment by HumanTree92** [comment]
That issue isn't really a huge bug. But to reproduce this:
1. Buy 2 different Handguns.
2. Store both Handguns.
3. Pull 1 Handgun out. (You will notice that you will have both the Ammo for both guns in 1.)
4. Get rid of the 1 gun you pulled out.
5. Grab other gun. (You will notice that it will not have any Ammo.)

There really isn't a fix for this as far as i can see. There was an issue where people where able to duplicate ammo to the max. People where able to put 2 guns in and repeatedly put them in & take them out to get 9999 ammo. So to fix that i put some menu.close throughout the client.lua so when a player puts in something it closes the menu completely. Same for if they take something out.

**Comment by tonibanks** [comment]
I see.. anyway from which part menu do i need to fixed?

**Comment by HumanTree92** [comment]
Well with the bug your having not sure if there is a fix. Maybe if there was a system where if there were 2 handguns it would only take half the ammo.

**Comment by tonibanks** [comment]
I tried to add close all menu after withdraw both pistol but they still dupping the ammo.

**Comment by HumanTree92** [comment]
To fix the problem that i had u need to add 

		elseif data.current.value == 'room_inventory' then
			menu.close() -- Add This
			OpenRoomInventoryMenu(property, owner)
		elseif data.current.value == 'player_inventory' then
			menu.close() -- Add This
			OpenPlayerInventoryMenu(property, owner)

You can find the above code under the OpenRoomMenu Function

**Comment by ElPumpo** [comment]
Fixed
