### ISSUE TITLE
Cant Open Deposit Item

### ISSUE THREAD

**Issue by tpoeschldk** [ESX-Org/esx_property#79]
Hello,

i have Some Problem with the Deposit of Items in my Property.

Error:
SCRIPT ERROR: @esx_property/client/main.lua:595: attempt to compare number with nil

Someone has an Idea?

**Comment by Wack1992** [comment]
I had this issue, I just had to revert to and old version of es_extended for now.

**Comment by HezimX** [comment]
line 534 in client/main.lua i just changed
`					label = item.label .. ' x' .. item.count,`
to
`					label = item.name .. ' x' .. item.count,`
