### ISSUE TITLE
No money when you sell

### ISSUE THREAD

**Issue by ElRocaYT** [ESX-Org/esx_property#8]
When you buy a house/office you can 'ENTER' or 'LEAVE' (locale.lua say is leave, but is sell).
Then when you sell, the property disappears of your properties but don't give money.

**Comment by JaroSound** [comment]
Bump

**Comment by chrisjbowen** [comment]
Change the following in server/main.lua to give back 100% of the price:

`RegisterServerEvent('esx_property:removeOwnedProperty')
AddEventHandler('esx_property:removeOwnedProperty', function(propertyName)

  local xPlayer = ESX.GetPlayerFromId(source)
  local property = GetProperty(propertyName)
  
  xPlayer.addMoney(property.price)
  RemoveOwnedProperty(propertyName, xPlayer.identifier)

end)`

If you want only a percentage to give back, then you'll need to do some math to get the price of the property being sold.

**Comment by djowdobom** [comment]
i've the same issue, any fix beyond?

**Comment by HumanTree92** [comment]
Yeah i have tested this out as well. If there is a Sell Option you should be able to get back some of your money.

**Comment by HumanTree92** [comment]
Any update on this?

**Comment by ElPumpo** [comment]
Yea you still dont get anything back when selling the properties you own.

**Comment by travisg17** [comment]
Anybody have a fix?

**Comment by ponduzn** [comment]
Heres how i added money back when selling a property for those interested:
server\main.lua:
line 176:
`RegisterServerEvent('esx_property:removeOwnedProperty')
AddEventHandler('esx_property:removeOwnedProperty', function(propertyName)
	local xPlayer = ESX.GetPlayerFromId(source)
	local property = GetProperty(propertyName)
	xPlayer.addMoney(property.price / 100 * 75)
	RemoveOwnedProperty(propertyName, xPlayer.identifier)
end)`

locales\en.lua:
line 29:
`['made_property'] = 'you have sold a property for ~g~75 percent ~w~of buy price',`

This will get 75% of buy price back to player.
Hope it helps someone.

**Comment by ponduzn** [comment]
Heres how i added money back when selling a property for those interested:
server\main.lua:
add this in "RegisterServerEvent('esx_property:removeOwnedProperty')" on line 176:

`
        local property = GetProperty(propertyName)
`
`
	xPlayer.addMoney(property.price / 100 * 75)
`



and this in locales\en.lua for notification:
line 29:
`['made_property'] = 'you have sold a property for ~g~75 percent ~w~of buy price',`

This will get 75% of buy price back to player.
Hope it helps someone.

**Comment by eoltw** [comment]
@ponduzn I tried your way, but I can always brush money.

**Comment by JohnHo258** [comment]
> Heres how i added money back when selling a property for those interested:
> server\main.lua:
> add this in "RegisterServerEvent('esx_property:removeOwnedProperty')" on line 176:
> 
> `local property = GetProperty(propertyName)`
> `xPlayer.addMoney(property.price / 100 * 75)`
> 
> and this in locales\en.lua for notification:
> line 29:
> `['made_property'] = 'you have sold a property for ~g~75 percent ~w~of buy price',`
> 
> This will get 75% of buy price back to player.
> Hope it helps someone.

It works but I can sell a rented house to get money. If I keep rent house and sell it, I can get unlimited money

**Comment by XvenDeR** [comment]
Maybe this will help
`function RemoveOwnedProperty(name, owner)

    local result = MySQL.Sync.fetchAll('SELECT rented FROM owned_properties WHERE name = @name AND owner = @owner',
    {
        ['@name'] = name,
        ['@owner'] = owner
    })
    
    if tonumber(result[1].rented) == 0 then
        local xPlayer = ESX.GetPlayerFromId(source)
        
        local getSellPrice = MySQL.Sync.fetchAll('SELECT price FROM properties WHERE name = @name',
    {
        ['@name'] = name
    })
        local cost = tonumber(getSellPrice[1].price)
        local lowEnd = cost/2
        local highEnd = cost*1.5
        local payment = math.random(lowEnd,highEnd)
        
        xPlayer.addAccountMoney('bank', payment)
        TriggerClientEvent('esx:showNotification', xPlayer.source, 'Bank recieved ~g~$'.. tostring(payment) ..' ~w~ from selling home')
    end

    MySQL.Async.execute('DELETE FROM owned_properties WHERE name = @name AND owner = @owner',
    {
        ['@name']  = name,
        ['@owner'] = owner
    }, function(rowsChanged)
        local xPlayer = ESX.GetPlayerFromId(source)

        if xPlayer then
            TriggerClientEvent('esx:showNotification', xPlayer.source, 'Property no longer owned')
        end
    end)
end`

Update the function. :)

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_property/commit/96c1ab491f924fc7e454f26eeeb45d07e475ded1
