### ISSUE TITLE
Script error ShowNotification

### ISSUE THREAD

**Issue by Patrickstek121** [ESX-Org/esx_property#81]
I get this error
SCRIPT ERROR: @esx_property/server/main.lua:26: attempt to call a nil value (field 'showNotification')

![image](https://user-images.githubusercontent.com/16652731/73110256-fff73980-3f05-11ea-9fc2-4639a32e22ce.png)

**Comment by SemirPro12** [comment]
Why is it closed? Is there any solution?

**Comment by iZerkahh** [comment]
Yes... Just change it to TriggerClientEvent('esx:showNotification', source, _U('not_enough'))
