### ISSUE TITLE
Can not open property menu after updating

### ISSUE THREAD

**Issue by MrHtgreen** [ESX-Org/esx_property#82]
I have delete all the old database files to do with this resource then put the new sql in and then replaced the actual resource and for some reason with the new update you can no longer open the property menu. But clients does work. Hope this can be resolved, thanks.

**Comment by MrHtgreen** [comment]
Fixed it, just scanned through the code and realised you had just forgot to put an end) at the end of a function on line 782, problem solved

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_property/commit/65abc5b490c56ab62052d715ebbdc8e102bb0790
