### ISSUE TITLE
Esx_property PROPERTY INVENTORY

### ISSUE THREAD

**Issue by DanyCryEn** [ESX-Org/esx_property#84]
hey, 
i've one problem with property inventory ... when i put items in the house inventory all works, but  when i try put out items of the house inventory this call me a error in the console.

it is this one:

SCRIPT ERROR: @esx_property/server/main.lua:228: attempt to call a nil value (field 'canCarryItem')
> handler (@esx_addoninventory/server/main.lua:82)
> handler (@esx_property/server/main.lua:222)

**Comment by MarcusFenix8840** [comment]
I also have this problem
