### ISSUE TITLE
dressing

### ISSUE THREAD

**Issue by montreuiljulien** [ESX-Org/esx_property#9]
il y a un probleme au niveau du dressing.

**Comment by RomainLanz** [comment]
??

**Comment by montreuiljulien** [comment]
dans le menu vêtements les joueurs on pas accès à leurs tenus.

**Comment by DNDdjay** [comment]
try this is the fxmanifest


dependencies {
	'async',
	'es_extended',
	'instance',
	'cron',
	'esx_addonaccount',
	'esx_addoninventory',
	'esx_datastore'
}
